<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ApproverDefinitions" targetNamespace="urn:Approver" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:app="urn:Approver" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <message name="rateMessage">
    <part name="rate" type="xsd:decimal">
    </part>
  </message>
  <message name="proposalMessage">
    <part name="name" type="xsd:string">
    </part>
    <part name="address" type="xsd:string">
    </part>
    <part name="amount" type="xsd:decimal">
    </part>
  </message>
  <portType name="loanPort">
    <operation name="approveOperation">
      <input message="app:proposalMessage">
    </input>
      <output message="app:rateMessage">
    </output>
    </operation>
  </portType>
  <binding name="loanBinding" type="app:loanPort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="approveOperation">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:Approver"/>
      </input>
      <output>
        <soap:body use="literal" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:Approver"/>
      </output>
    </operation>
  </binding>
  <service name="ApproverService">
    <port name="ApproverLoan" binding="app:loanBinding">
      <soap:address location="http://127.0.0.1:8080/axis2_war/services/ApproverService"/>
    </port>
  </service>
</definitions>
